# Generated by Django 4.1.4 on 2022-12-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='voted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
