# Generated by Django 4.1.4 on 2022-12-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_vote_remove_choice_voted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
