# Generated by Django 4.1.4 on 2022-12-19 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_choice_votes_alter_vote_vote_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote_text',
            new_name='pk_choice',
        ),
    ]
