# Generated by Django 4.1.4 on 2022-12-19 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_rename_vote_text_vote_pk_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='pk_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.choice'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voted_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
